import Head from 'next/head';
import Image from 'next/image';
import css from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={css.container}>
      <header className={css.header}>
        <nav className={css.navbar}>
          <div className={css.navDiv}>
            <a className={css.navbarBrand}>
              <img src='logo.svg' alt='logo' />
            </a>
            <div className={[css.navItems, css.test].join(' ')}>
              <ul className={css.navList}>
                <li className={css.navListItem}>
                  <a className={css.navLink} href=''>
                    تماس با ما
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={css.main}>
        <h1 className={css.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={css.description}>
          Get started by editing <code className={css.code}>pages/index.tsx</code>
        </p>

        <div className={css.grid}>
          <a href='https://nextjs.org/docs' className={css.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={css.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/canary/examples' className={css.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
            className={css.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={css.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={css.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
